apiVersion: v1
kind: Service
metadata:
  name: secure-task-manager-service
spec:
  type: NodePort
  selector:
    app: secure-task-manager
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007